/**
 * Real Sikkim elevation store.
 *
 * Loads the DEM generated by `scripts/build-sikkim-dem.mjs`
 * (public/assets/terrain/sikkim.dem.bin + .json) once into memory as a
 * synchronous-access Uint16 grid so geometry, markers, collisions and camera
 * routes can all read real metre elevations without awaiting an async fetch
 * per query.
 *
 * Copernicus DEM GLO-30, CC BY 4.0 (attribution in documentation/DATA_SOURCES.md).
 */

export interface DemMeta {
  format: string
  width: number
  height: number
  bounds: { west: number; south: number; east: number; north: number }
  minM: number
  maxM: number
  source: string
  license: string
  attribution: string
  notes: string
}

let elev: Uint16Array | null = null
let meta: DemMeta | null = null
let pending: Promise<void> | null = null

async function load(): Promise<void> {
  try {
    const metaRes = await fetch('/assets/terrain/sikkim.dem.json')
    meta = (await metaRes.json()) as DemMeta
    const binRes = await fetch('/assets/terrain/sikkim.dem.bin')
    const buf = await binRes.arrayBuffer()
    elev = new Uint16Array(buf)
  } catch (err) {
    // Never block the experience on terrain data; geometry degrades to a
    // low-relief surface and marker placement falls back to the datum.
    console.warn('[terrain] elevation data unavailable', err)
    elev = new Uint16Array(0)
  }
}

/** Idempotent loader; safe to call from many component mounts. */
export function ensureTerrainLoaded(): Promise<void> {
  if (elev) return Promise.resolve()
  if (pending) return pending
  pending = load()
  return pending
}

export function terrainReady(): boolean {
  return !!elev && elev.length > 0
}

export function getDem(): { meta: DemMeta | null; elev: Uint16Array | null } {
  return { meta, elev }
}

const NO_DATA = new Uint16Array(0)

/**
 * Real elevation (metres above sea level) at a geographic coordinate.
 * Returns 0 when data is not yet loaded.
 */
export function getElevationMAtLatLon(lat: number, lon: number): number {
  const grid = elev ?? NO_DATA
  const m = meta
  if (!m || grid.length === 0) return 0
  const w = m.width
  const h = m.height
  const b = m.bounds
  if (
    lat < b.south ||
    lat > b.north ||
    lon < b.west ||
    lon > b.east
  ) {
    return 0
  }
  const ix = Math.round(((lon - b.west) / (b.east - b.west)) * (w - 1))
  const iy = Math.round(((b.north - lat) / (b.north - b.south)) * (h - 1))
  const c = Math.max(0, Math.min(w - 1, ix))
  const r = Math.max(0, Math.min(h - 1, iy))
  return grid[r * w + c]
}
